title: Instrukcja użytkownika Supla Cloud
description: Supla Cloud dla początkujacych
theme: just-the-docs

url: https://jaku2019.github.io/Supla_wiki

aux_links:
  Template Repository: https://jaku2019.github.io/Supla_wiki

plugins:
  - jekyll-default-layout
